name: copy_with_demo
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  analyzer_kit_annotation: any

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6